### ISSUE TITLE
Get the right NSProgress (or ASDProgress)

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#3]
Getting an NSProgress object for the actual install progress instead of relying on the home screen SBDownloadIcon, which will post a notification only when the view will appear.

**Comment by RuntimeOverflow** [comment]
I have tried to find another way, but I haven't been successful. There is a framework called InstallCoordinator, which handles downloads/updates.

**Comment by lgariv** [comment]
> I have tried to find another way, but I haven't been successful. There is a framework called InstallCoordinator, which handles downloads/updates.

I found in the AppStoreDaemon framework, in ASDAppQuery there's a subclass of NSProgress called ASDProgress that tracks the installation progress in an observable object.

I don't know if it can be passed as an NSProgress to the observedProgress property of the UIProgressView to track it dynamically, but it is definitely worth a try.

**Comment by lgariv** [comment]
@RuntimeOverflow Just went over some of the installCoordination headers, and it seems to me that it's purpose is to get the already downloaded archive, extract it, install it to the device, and restore user data (from previous installations, if any) - basically everything that happens relatively quick on the last 30-40 percent of the process.
It is also responsible for uninstalling apps.

But apparently it does not track the download progress.

**Comment by RuntimeOverflow** [comment]
Oh ok I'll see if I can get something working with ASDProcess.

**Comment by lgariv** [comment]
> Oh ok I'll see if I can get something working with ASDProcess.

@RuntimeOverflow Just remembered that I tried using KeyValueObserver the other day, but didn't get to finish that part (probably won't get to it today as well).

I'd go this route actually instead of passing the pointer to the object and then trying to cast it in some way. If it works, it is a much cleaner code and way more efficient.

**Comment by RuntimeOverflow** [comment]
@lgariv I couldn't really manage to get something working, because it seems ASDApp, ASDPrgress, etc. are never used. However, I found what we need. It's the CoreServices Framework. It includes LSInstallProgressList, which conveniently keeps track of all install progresses (as NSProgress classes). The actual progress seems to be managed by FBSApplicationPlaceholder, a class belonging to FrontBoardServices. I'll dig around, but I'm sure we're on the right track. We could just use LSInstallProgressList, but  FBSApplicationPlaceholder also handles pausing etc. so we have additional information, which would be missing if we're just relying on NSProgress. For example we could make the user tap on the notification to pause/resume the download.

**Comment by lgariv** [comment]
@RuntimeOverflow Does LSInstallProgressList actually tracks the download step? Or is it just tracking the install progress similarly to installCoordinator?

**Comment by RuntimeOverflow** [comment]
It does but I'm already done implementing and it works. You just need to accept my pull request and I'll make a new one. (Also read the comment on the pull request)

**Comment by RuntimeOverflow** [comment]
@lgariv Implemented. (See Pull Request #13) And yes it tracks the download + installation, however, I chose to not use LSInstallProgressList in the end and go for an FBSApplicationPlaceholder hook, so basically, we have complete control over pausing/unpausing and prioritizing the download.
